version: 2
jobs:
  echo:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "starting CI suite"
  install:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
  start:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run start
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run test
workflows:
  version: 2
  whole_suite:
    jobs:
      # echo and install will be run in parallel
      - echo
      - install

      # install will have to complete before start and test can be started
      - start:
          requires:
            - install
      - test:
          requires:
            - install